#Variables
@baseUrl = http://localhost:8080

#Health check
# @name healthCheck
GET {{baseUrl}}/health

###

#GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
POST {{baseUrl}}/rooms
# @name createRoom
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{getRooms.response.body.$.[0].id}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
POST {{baseUrl}}/rooms/417c0425-0dcc-4860-8345-6dce5a2a11be/questions
# @name createQuestion
Content-Type: application/json

{
    "question": "O que é Vue.js?"
}
